import { sourced } from './provenance.js';

export const ARENA = Object.freeze({
  sideWallX: sourced({
    value: 4096,
    unit: 'uu',
    status: 'verified',
    source: 'RLBot useful game values',
    confidence: 0.99,
  }),
  sideWallHalfLength: sourced({
    value: 3968,
    unit: 'uu',
    status: 'derived',
    source: 'Half of the published 7936 uu side-wall length',
    confidence: 0.99,
  }),
  backWallY: sourced({
    value: 5120,
    unit: 'uu',
    status: 'verified',
    source: 'RLBot useful game values',
    confidence: 0.99,
  }),
  backWallHalfLength: sourced({
    value: 2944,
    unit: 'uu',
    status: 'derived',
    source: 'Half of the published 5888 uu back-wall length',
    confidence: 0.99,
  }),
  cornerPlaneIntercept: sourced({
    value: 8064,
    unit: 'uu',
    status: 'verified',
    source: 'RLBot useful game values: 45-degree corner planes intersect both axes at ±8064',
    confidence: 0.99,
  }),
  cornerWallLength: sourced({
    value: 1629.174,
    unit: 'uu',
    status: 'verified',
    source: 'RLBot useful game values',
    confidence: 0.99,
  }),
  floorWallCurveRadius: sourced({
    value: 256,
    unit: 'uu',
    status: 'temporary',
    source: 'Analytic quarter-curve baseline pending standard-arena mesh measurement',
    confidence: 0.35,
    notes: 'Functional continuity value; not presented as an exact Rocket League measurement.',
  }),
  ceilingWallCurveRadius: sourced({
    value: 256,
    unit: 'uu',
    status: 'temporary',
    source: 'Analytic quarter-curve baseline pending standard-arena mesh measurement',
    confidence: 0.3,
    notes: 'Functional continuity value; not presented as an exact Rocket League measurement.',
  }),
  ceilingZ: sourced({
    value: 2044,
    unit: 'uu',
    status: 'verified',
    source: 'RLBot useful game values',
    confidence: 0.99,
  }),
  goalHeight: sourced({
    value: 642.775,
    unit: 'uu',
    status: 'verified',
    source: 'RLBot useful game values',
    confidence: 0.99,
  }),
  goalHalfWidth: sourced({
    value: 892.755,
    unit: 'uu',
    status: 'verified',
    source: 'RLBot useful game values',
    confidence: 0.99,
  }),
  goalDepth: sourced({
    value: 880,
    unit: 'uu',
    status: 'verified',
    source: 'RLBot useful game values',
    confidence: 0.99,
  }),
});
